'use client';
import {useEffect,useRef,useState,type ReactNode,type MouseEvent} from 'react';
import {motion,AnimatePresence,MotionConfig} from 'motion/react';
import {asset,nav,services,stages,companies,systems,contact,directExperience} from '@/lib/content';
import Signal from './Signal';
import SectionPhoto from './SectionPhoto';
import HeroDetail,{HeroCount,ProofCount} from './HeroDetail';
import RevealHeading from './RevealHeading';
import ThemeToggle from './ThemeToggle';
import Markets from './Markets';
import CvViewer from './CvViewer';

function Arrow({diagonal=false}:{diagonal?:boolean}){return <span aria-hidden="true" className="arrow">{diagonal?'↗':'→'}</span>;}
function Label({number,children}:{number:string;children:ReactNode}){return <div className="section-label"><span>{number}</span><span>{children}</span><span className="label-rule"/></div>;}
function Magnetic({children,className='',...props}:{children:ReactNode;className?:string;href?:string;onClick?:()=>void}){
 const move=(e:MouseEvent<HTMLElement>)=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches||!matchMedia('(pointer: fine)').matches)return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--mx',`${(e.clientX-r.left-r.width/2)*.09}px`);e.currentTarget.style.setProperty('--my',`${(e.clientY-r.top-r.height/2)*.09}px`);};
 const reset=(e:MouseEvent<HTMLElement>)=>{e.currentTarget.style.setProperty('--mx','0px');e.currentTarget.style.setProperty('--my','0px');};
 return props.href?<a {...props} className={`magnetic ${className}`} onMouseMove={move} onMouseLeave={reset}>{children}</a>:<button {...props} className={`magnetic ${className}`} onMouseMove={move} onMouseLeave={reset}>{children}</button>;
}
function CvLink({className='',onClick}:{className?:string;onClick?:()=>void}){return <a className={className} href="#cv" onClick={onClick}>VIEW CV <Arrow diagonal/></a>;}
function useDialog(open:boolean,ref:React.RefObject<HTMLDialogElement|null>,close:()=>void){
 useEffect(()=>{
  const dialog=ref.current;if(!dialog)return;
  if(!open){if(dialog.open)dialog.close();return;}
  const before=document.activeElement as HTMLElement|null;
  dialog.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';
  const cancel=(event:Event)=>{event.preventDefault();close();};dialog.addEventListener('cancel',cancel);
  return ()=>{dialog.removeEventListener('cancel',cancel);if(dialog.open)dialog.close();document.body.style.overflow=overflow;before?.focus();};
 },[open,ref,close]);
}
// Native dialogs supply keyboard containment and Escape behavior.
function VideoPlayer({open,close}:{open:boolean;close:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);const video=useRef<HTMLVideoElement>(null);const [error,setError]=useState(false);
 useDialog(open,ref,close);
 useEffect(()=>{if(open){setError(false);video.current?.play().catch(()=>{});}else video.current?.pause();},[open]);
 return <dialog ref={ref} className="video-dialog" aria-labelledby="video-title" onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="video-shell"><div className="dialog-heading"><div><span className="eyebrow">08 / INTRODUCTION</span><h2 id="video-title">Meet Abdulrahman.</h2></div><button className="close-button" onClick={close} aria-label="Close introduction">×</button></div>{open&&<video ref={video} controls controlsList="nodownload" playsInline draggable={false} onContextMenu={event=>event.preventDefault()} onDragStart={event=>event.preventDefault()} preload="metadata" poster={asset('intro-poster.jpg')} onError={()=>setError(true)}><source src={asset('intro.mp4')} type="video/mp4" onError={()=>setError(true)}/></video>}{error&&<p className="media-error">The introduction is temporarily unavailable. <a href={`mailto:${contact.email}`}>Start a conversation by email →</a></p>}<div className="video-foot"><span>REAL CONVERSATIONS. REAL CONTEXT.</span><CvLink onClick={close}/></div></div></dialog>;
}
export default function Portfolio(){
 const [active,setActive]=useState('top');const [menu,setMenu]=useState(false);const [command,setCommand]=useState(false);const [query,setQuery]=useState('');
 const [videoOpen,setVideoOpen]=useState(false);const [service,setService]=useState(0);const [company,setCompany]=useState(0);const [stage,setStage]=useState(0);const [tool,setTool]=useState(0);const [portraitError,setPortraitError]=useState(false);
 const menuRef=useRef<HTMLDialogElement>(null);const commandRef=useRef<HTMLDialogElement>(null);const cursor=useRef<HTMLDivElement>(null);
 const closeMenu=useRef(()=>setMenu(false)).current;const closeCommand=useRef(()=>setCommand(false)).current;const closeVideo=useRef(()=>setVideoOpen(false)).current;
 useDialog(menu,menuRef,closeMenu);useDialog(command,commandRef,closeCommand);
 useEffect(()=>{
  const sections=[...document.querySelectorAll<HTMLElement>('main section[id]')];
  const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('entered');});},{threshold:.12});sections.forEach(s=>observer.observe(s));
  let scheduled=false;
  const update=()=>{scheduled=false;let id='top';for(const section of sections){if(section.getBoundingClientRect().top<=window.innerHeight*.35)id=section.id;}setActive(id);const max=document.documentElement.scrollHeight-window.innerHeight;document.documentElement.style.setProperty('--page-progress',String(max>0?Math.min(1,Math.max(0,window.scrollY/max)):0));};
  const scroll=()=>{if(!scheduled){scheduled=true;requestAnimationFrame(update);}};
  const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setQuery('');setCommand(v=>!v);}};
  const pointer=(event:PointerEvent)=>{if(!matchMedia('(hover: hover) and (pointer: fine) and (prefers-reduced-motion: no-preference)').matches)return;document.documentElement.dataset.cursor='on';if(cursor.current){cursor.current.style.transform=`translate3d(${event.clientX}px,${event.clientY}px,0)`;cursor.current.dataset.interactive=String(!!(event.target as Element).closest('a,button'));}};
  const leave=(event:PointerEvent)=>{if(!event.relatedTarget)delete document.documentElement.dataset.cursor;};window.addEventListener('pointerout',leave);
  window.addEventListener('resize',scroll);window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('keydown',key);window.addEventListener('pointermove',pointer,{passive:true});update();
  return ()=>{observer.disconnect();window.removeEventListener('pointerout',leave);delete document.documentElement.dataset.cursor;window.removeEventListener('resize',scroll);window.removeEventListener('scroll',scroll);window.removeEventListener('keydown',key);window.removeEventListener('pointermove',pointer);};
 },[]);
 const go=(id:string)=>{setMenu(false);setCommand(false);location.hash=id;};
 return <MotionConfig reducedMotion="user"><a href="#about" className="skip-link">Skip to content</a><div ref={cursor} className="cursor-light" aria-hidden="true"/><div className="page-progress" aria-hidden="true"/>
 <header className="header"><a href="#top" className="brand" aria-label="Abdulrahman Zidan — home"><img className="brand-portrait" src={asset('profile.webp')} width="48" height="48" alt="Abdulrahman Zidan"/><span className="brand-label">ABDULRAHMAN<br/>ZIDAN</span></a><nav aria-label="Main navigation" className="desktop-nav">{nav.map(name=><a key={name} href={`#${name.toLowerCase()}`} aria-current={active===name.toLowerCase()?'location':undefined}>{name}</a>)}</nav><div className="header-actions"><ThemeToggle/><button className="command-toggle" aria-label="Open command menu" onClick={()=>{setQuery('');setCommand(true);}}>⌘ K</button><a className="hire" href="#contact">LET’S TALK <Arrow diagonal/></a><button className="menu-toggle" aria-label="Open navigation" onClick={()=>setMenu(true)}>MENU <span>☰</span></button></div></header>
 <main>
 <section id="top" className="hero"><div className="hero-topline"><span><i className="live-dot"/> AVAILABLE FOR REMOTE WORK</span><span>CAIRO, EGYPT ↗ U.S. TEAMS</span></div><div className="hero-grid"><div className="hero-copy"><p className="eyebrow">REAL ESTATE SALES / LEAD MANAGEMENT</p><h1><span className="hero-name-first">Abdulrahman</span><br/><span className="hero-name-last">Zidan<span className="accent">.</span></span></h1><p className="hero-brief">3+ years turning U.S. real estate conversations into opportunities.</p><p className="hero-statement">Conversations.<br/><em>Qualified opportunities.</em></p><div className="hero-credentials"><HeroCount value={3} suffix="+" label="YEARS IN REAL ESTATE"/><HeroCount value={13} label="U.S. MARKETS"/></div><div className="hero-ctas"><Magnetic href="#contact" className="button-primary">LET’S WORK TOGETHER <Arrow diagonal/></Magnetic><Magnetic onClick={()=>setVideoOpen(true)} className="button-text"><span className="play-mini">▶</span> MEET ME <span className="muted">01:07</span></Magnetic></div></div><Signal/></div><HeroDetail/><div className="hero-bottom"><span>COLD CALLER · LEAD MANAGER<br/>APPOINTMENT SETTER · VIRTUAL ASSISTANT</span><a href="#about" className="scroll-prompt">EXPLORE THE SIGNAL <span>↓</span></a><span className="hero-index">PERSONAL PORTFOLIO<br/>VOL. 01 / SIGNAL</span></div></section>
 <div className="ticker" aria-hidden="true"><div>PEOPLE FIRST. <span>PIPELINE FORWARD.</span> PEOPLE FIRST. <span>PIPELINE FORWARD.</span> PEOPLE FIRST. <span>PIPELINE FORWARD.</span></div></div>
 <section id="about" className="section about"><Label number="01">THE PERSON BEHIND THE PIPELINE</Label><div className="about-grid"><div className="portrait-wrap"><div className="portrait-corner">AZ / 01</div>{!portraitError?<img src={asset('profile.webp')} alt="Abdulrahman Zidan in a black blazer and glasses" width="640" height="640" loading="lazy" onError={()=>setPortraitError(true)}/>:<div className="portrait-fallback">AZ<span>Abdulrahman Zidan</span></div>}<span className="portrait-cross" aria-hidden="true">+</span><div className="portrait-caption"><span>ABDULRAHMAN ZIDAN</span><span>CAIRO / EGYPT</span></div></div><div className="about-copy"><RevealHeading>People.<br/>{' '}Context.<br/><em>Ownership.</em></RevealHeading><p className="lead">Not another caller reading a script.<br/>A sales operator built for the pipeline.</p><p>I bring 3+ years of U.S. real estate cold-calling experience, with approximately one year of hands-on Lead Manager work with U.S. clients and investors.</p><p>{directExperience}</p><p>From seller motivation to the next follow-up, I keep the conversation human and the context clear. Experience in real estate and solar has taught me how those fundamentals transfer across industries.</p><div className="education-note"><span className="tiny-label">ALSO WIRED FOR SYSTEMS</span><p>Computer Science student<br/>Modern Academy for Computer Science and Technology.</p></div><div className="inline-links"><CvLink/><button onClick={()=>setVideoOpen(true)}>WATCH INTRODUCTION <Arrow diagonal/></button></div><SectionPhoto section="about"/></div></div></section>
 <section id="services" className="section services"><Label number="02">WAYS TO WORK TOGETHER</Label><div className="section-heading"><RevealHeading>One skillset.<br/><em>Four ways forward.</em></RevealHeading><p>The role can change. Communication,<br/>qualification and ownership stay.</p></div><div className="service-grid"><div className="service-list" role="tablist" aria-label="Services">{services.map((item,i)=><button role="tab" aria-selected={service===i} id={`service-tab-${i}`} aria-controls="service-panel" key={item.name} onClick={()=>setService(i)} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const next=(service+(e.key==='ArrowDown'?1:3))%4;setService(next);document.getElementById(`service-tab-${next}`)?.focus();}}} tabIndex={service===i?0:-1} className={service===i?'selected':''}><span className="tiny-label">0{i+1}</span><span>{item.name}</span><Arrow diagonal/></button>)}</div><div id="service-panel" role="tabpanel" aria-labelledby={`service-tab-${service}`} className="service-panel"><AnimatePresence mode="wait" initial={false}><motion.div key={service} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.22}}><div className="service-photo-row"><div className="service-orbit" aria-hidden="true"><span>{String(service+1).padStart(2,'0')}</span><i/></div><SectionPhoto section="services"/></div><h3>{services[service].verb}</h3><p>{services[service].text}</p><ul>{services[service].details.map(item=><li key={item}><span>↗</span>{item}</li>)}</ul><a href="#contact" className="inline-cta">LET’S TALK ABOUT THIS ROLE <Arrow/></a></motion.div></AnimatePresence></div></div></section>
 <section id="method" className="section method"><Label number="03">THE SIGNAL PATH</Label><div className="section-heading"><RevealHeading>Every lead deserves<br/><em>a clear next step.</em></RevealHeading><p>Explore the method.<br/>From first hello to clean handoff.</p></div><div className="method-path" style={{'--stage':stage} as React.CSSProperties}>{stages.map((item,i)=><button key={item.name} aria-pressed={stage===i} className={stage===i?'selected':''} onClick={()=>setStage(i)}><span className="path-node"><span>0{i+1}</span></span><strong>{item.name}</strong><span>{item.text}</span></button>)}</div><div className="method-detail" aria-live="polite"><span className="tiny-label">0{stage+1} / {stages[stage].name.toUpperCase()}</span><p>{stages[stage].detail}</p><Arrow/></div></section>
 <section id="experience" className="section experience"><Label number="04">EXPERIENCE, IN CONTEXT</Label><div className="section-heading"><RevealHeading>From first contact<br/><em>to pipeline ownership.</em></RevealHeading><p>Cold Caller → Lead Manager<br/>U.S. real estate + solar</p></div><div className="career-strip"><div><span>3+ YEARS</span><strong>Cold calling</strong></div><span className="career-arrow">↗</span><div><span>~1 YEAR / HANDS-ON</span><strong>Lead management</strong></div><p>Qualify. Follow up. Keep the context.<br/>Prepare the opportunity for acquisitions.</p></div><div className="direct-experience"><span>2+ YEARS / DIRECT COLLABORATION</span><p>{directExperience}</p></div><div className="experience-grid"><div className="company-list" aria-label="Companies and teams">{companies.map((item,i)=><button key={item.name} className={company===i?'selected':''} aria-pressed={company===i} onClick={()=>setCompany(i)}><span>0{i+1}</span>{item.name}<Arrow diagonal/></button>)}</div><div className="company-panel"><span className="tiny-label">COMPANIES & TEAMS / EXPERIENCE</span><AnimatePresence mode="wait" initial={false}><motion.div key={company} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.2}}><h3>{companies[company].name}<span className="accent">.</span></h3><p>{companies[company].text}</p></motion.div></AnimatePresence><SectionPhoto section="experience"/><div className="company-panel-footer"><span>COMMUNICATION</span><span>QUALIFICATION</span><span>FOLLOW-THROUGH</span></div></div></div></section>
 <Markets/>
 <section id="proof" className="section proof"><Label number="06">PROOF OF FIT</Label><RevealHeading>Built on experience.<br/><em>Grounded in the work.</em></RevealHeading><div className="proof-grid"><div><ProofCount value={3} suffix="+"/><h3>Years in U.S. real estate</h3><p>Homeowner conversations, seller qualification and consistent follow-up.</p></div><div><ProofCount value={2} pad={2}/><h3>Core industries</h3><p>Real estate and solar. Shared fundamentals, different conversations.</p></div><div><strong className="proof-word">CALLER<br/><span>↗ MANAGER</span></strong><h3>A progression in ownership</h3><p>From generating the lead to managing the context and the next action.</p></div></div><SectionPhoto section="proof"/><div className="proof-bottom"><span className="live-dot"/><p>Recognized as a top achiever. Usually met or exceeded performance expectations.</p><span>NO SHORTCUTS. CLEAR FOLLOW-THROUGH.</span></div></section>
 <section id="systems" className="section systems"><Label number="07">SYSTEMS</Label><div className="section-heading"><RevealHeading>Comfortable where<br/><em>people meet systems.</em></RevealHeading><p>The tools can change. I learn the stack,<br/>keep the data clean and make<br/>the next action obvious.</p></div><div className="systems-grid"><div className="system-map"><div className="system-core"><span className="live-dot"/>THE NEXT ACTION</div><div className="tool-list">{systems.map((item,i)=><button key={item.name} onClick={()=>setTool(i)} aria-pressed={tool===i} className={tool===i?'selected':''}><span className="tool-dot"/><span>{item.name}{i===0&&<small>GHL</small>}</span><span className="tool-category">{item.group}</span><Arrow diagonal/></button>)}</div></div><div className="system-detail"><span className="tiny-label">STACK EXPLORER / {systems[tool].label}</span><h3>{systems[tool].name}</h3><p aria-live="polite">{systems[tool].text}</p><SectionPhoto section="systems"/><div className="system-flow"><span>PEOPLE</span><i>→</i><span>CONTEXT</span><i>→</i><span>ACTION</span></div><span className="system-note">CRM SYSTEMS / PIPELINE MANAGEMENT / FOLLOW-UP WORKFLOWS</span></div></div></section>
 <section id="introduction" className="section introduction"><Label number="08">A HUMAN INTRODUCTION</Label><div className="section-heading"><RevealHeading>Hear the person.<br/><em>Not just the pitch.</em></RevealHeading><p>A little over a minute.<br/>A better sense of who you’ll work with.</p></div><button className="video-card" onClick={()=>setVideoOpen(true)} aria-label="Play Abdulrahman’s introduction"><img src={asset('intro-poster.jpg')} alt="Abdulrahman speaking in his introduction video" width="1280" height="720" loading="lazy"/><span className="video-shade"/><span className="video-card-top"><span><i className="live-dot"/> ON THE OTHER END OF THE LINE</span><span>01:07 / INTRODUCTION</span></span><span className="play-disc">▶</span><span className="video-card-bottom"><span>Meet<br/><em>Abdulrahman.</em></span><span className="video-action">PLAY INTRODUCTION <Arrow diagonal/></span></span></button><SectionPhoto section="introduction"/><div className="cv-strip"><div><span className="tiny-label">THE FULL BACKGROUND</span><p>Conversation first. Credentials close by.</p></div><CvLink className="cv-button"/></div></section>
 <CvViewer/>
 <section id="contact" className="section contact"><Label number="10">THE NEXT CONVERSATION</Label><div className="contact-status"><span className="live-dot"/> AVAILABLE FOR REMOTE WORK / WORKING WITH U.S. TEAMS</div><RevealHeading>Let’s make<br/>the next conversation<br/><em>count<span className="accent">.</span></em></RevealHeading><Magnetic href={`mailto:${contact.email}`} className="contact-email">{contact.email}<Arrow diagonal/></Magnetic><div className="contact-bottom"><div className="inline-links"><a href={contact.linkedin} target="_blank" rel="noreferrer">LINKEDIN <Arrow diagonal/></a><a href={contact.telegram} target="_blank" rel="noreferrer">TELEGRAM <Arrow diagonal/></a><CvLink/><button onClick={()=>setVideoOpen(true)}>INTRODUCTION <Arrow diagonal/></button></div><span>CAIRO, EGYPT<br/>REMOTE / U.S. TEAMS</span></div><SectionPhoto section="contact"/></section>
 </main><footer><a href="#top" className="footer-brand">A.Z</a><span>© {new Date().getFullYear()} ABDULRAHMAN ZIDAN</span><span>PEOPLE FIRST. PIPELINE FORWARD.</span><a href="#top">BACK TO TOP ↑</a></footer>
 <dialog ref={menuRef} className="menu-dialog" aria-labelledby="menu-title"><div className="dialog-heading"><h2 id="menu-title">Explore.</h2><button className="close-button" onClick={closeMenu} aria-label="Close navigation">×</button></div><nav aria-label="Mobile navigation">{nav.map((name,i)=><a key={name} href={`#${name.toLowerCase()}`} onClick={closeMenu}><span>0{i+1}</span>{name}<Arrow diagonal/></a>)}</nav><a className="button-primary" href="#contact" onClick={closeMenu}>HIRE ME <Arrow diagonal/></a></dialog>
 <dialog ref={commandRef} className="command-dialog" aria-labelledby="command-title"><div className="dialog-heading"><h2 id="command-title">Go somewhere.</h2><button className="close-button" onClick={closeCommand} aria-label="Close command menu">×</button></div><input aria-label="Search sections" placeholder="Search the portfolio…" value={query} onChange={e=>setQuery(e.target.value)} autoFocus/><div className="command-results">{[...nav,'View CV','LinkedIn','Telegram'].filter(name=>name.toLowerCase().includes(query.toLowerCase())).map(name=>name==='View CV'?<CvLink key={name} onClick={closeCommand}/>:name==='LinkedIn'||name==='Telegram'?<a key={name} href={contact[name.toLowerCase() as 'linkedin'|'telegram']} target="_blank" rel="noreferrer" onClick={closeCommand}>{name}<Arrow diagonal/></a>:<button key={name} onClick={()=>go(name.toLowerCase())}>{name}<Arrow/></button>)}</div><p className="tiny-label">ESC TO CLOSE / CTRL OR CMD + K TO OPEN</p></dialog>
 <VideoPlayer open={videoOpen} close={closeVideo}/>
 </MotionConfig>;
}
